[package]
name = "ant_mania"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
tempfile = "3.0"
criterion = "0.5"

[[bench]]
name = "simulation_bench"
harness = false

[[bench]]
name = "real_map_bench"
harness = false

[[bench]]
name = "micro_bench"
harness = false
